version: '3'

services:
  service1:
    image: service1
    container_name: service1
    ports:
      - 8001:8001
    environment:
      - SERVICE2_IP=service2:8002
    networks:
      - service-nw

  service2:
    image: service2
    container_name: service2
    ports:
      - 8002:8002
    networks:
      - service-nw

networks:
  service-nw: