[package]
name = "service1"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rocket = "0.5"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket_contrib]
version = "0.4.11"
default-features = false
features = ["json"]